[1단계] 박준태 미션 제출합니다.
CNU-SPICY/java-blackjack pull request #2
Opened 2024-01-19 05:00 UTC by juntae6942

2024-01-20 19:53 UTC, Sunkist18 requested changes
생각보다 리뷰할 거리가 많아서 아침에 더 해드릴게요

우선적으로 책임에 대한 분리, 코드 일관성, 코드 중복, 명명규칙, 
코드직관성, 코드확장가능성, 상수 처리에 대해 리뷰했습니다.

리뷰를 하다보면 제 말투가 공격적으로 느껴지실 수 있어서 
말끝마다 이모지를 붙혀봤습니다 😄 

> 번창하세요

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/view/OutputView.java
> +    public void playerResult(PlayerDto playerDto) {
dealerResult와 playerResult에서 비슷한 코드가 반복수행되고 있네요 😄

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/service/PlayGameService.java
> +    public DealerDto returnDealerState() {
return이라는 네이밍을 사용한 이유가 있을까요? 💭

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/service/PlayGameService.java
> +        return !duplicatedCheckCard.contains(card);
duplicatedCheckCard를 Set으로 변경하는건 어떨까요? 
contains의 시간복잡도가 훨씬 단축될 것 같아요 👍

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/service/PlayGameService.java
> +    public void gameStart() {
gameStart 메소드는 게임 시작 뿐만 아니라 초기 카드 배분과 결과 메시지 출력까지 담당하고 있네요 
더 작은 메서드로 나눠보는건 어떨까요 💭

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean scoreIsLowerThen16() {
16이라는 매직넘버가 메소드명에 존재하네요 😱 
만약에 게임의 규칙이 변경되어서 16이 아닌 숫자로 변경된다면❓❓

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Player.java
> +            score+=10;
에이스가 1 또는 11 이라서 이런식으로 작성한 것 같은데.
코드만 보고서는 원래의 의도를 파악하기는 힘들어보여요 😢

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Player.java
> +        return cards.contains(new Card(CardSymbol.SPADE,1));
Ace가 존재하는 지 확인하는 코드일까요?
그런데 코드에서 보면 CardSymbol에서 왜 SPADE를 사용한 걸까요?

스페이드 에이스만 에이스로 판단하는 걸까요?
아니면 문양에 관계없이 값이 1인 카드가 존재하는 지 확인하는 걸까요?
아무것도 모르는 사람이 이 코드를 보면 판단 할 수 있을까요?

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Card.java
> +        return this.symbol.equals(CardSymbol.SPADE) && this.cardNumber==1;
SPACE 에이스만 에이스인가요?
다이아몬드, 하트, 클로버 에이스도 모두 에이스입니다 😄 
차별금지 🚫

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/CardSymbol.java
> +public enum CardSymbol {
CardSymbol이라는 enum class 에서
randomSymbol과 randomValue를 사용하는 것이 맞을까요?

RandomCardValueGenerator의 역할을 CardSymbol이 맡아서 하고 있는 건 아닐까요?

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Dealer.java
> +    private static final int REPEAT_LIMIT = 16;
REPEAT_LIMIT 라고 하면
반복할 수 있는 최대 값이라고 오해하지는 않을까요?

변수명을 수정해보는 건 어떨까요? 🤔

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/dto/CardDto.java
> +    int num;
어떤 코드에서는 cardNumber로 사용하던데,
정작 CardDto에서는 num이라는 number의 축약형을 사용하고 있네요

축약형 절대금지 🚫 number로 사용해보는 건 어떨까요? 
코드의 통일성을 위해서라도요 👻

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Dealer.java
> +    private void checkIsAceAndChange(Card card) {
아래 플레이어의 checkAndChangeCard와 다른 점이 뭔가요?
같은 기능을 하는 코드인데 중복되게 둘 다 적혀있고, 메소드 이름은 또 다르네요 😓 

지금 보니 딜러와 플레이어에서 중복코드가 굉장히 많은데, 이렇게 되면 하나의 로직을 수정하면
두 개의 클래스를 바라보며 수정해야해서 좋은 코드는 아닌 것 같아요 😞

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Player.java
> +    private static final int CHANGE_LIMIT = 11;
CHANGE_LIMIT이 말하고자 하는게 뭔지 이해하기 어려워요!
다른 상수명을 고민해보는 건 어떨까요? 🤔

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/domain/Player.java
> +    public boolean aceIsCanChange() {
is Can... 보다는
~able 방식으로 명명해보는건 어떨까요?
혹은 그냥 canChange같은 형식으로요
isCanChange는 어색해보여요!

2024-01-20 19:53 UTC, Sunkist18 commented on src/main/java/blackjack/view/InputView.java
> +public class InputView {
게임에서 출력하는 메세지들을 모두 Enum 처리해서 관리해보는건 어떨까요?

2024-01-21 02:47 UTC, juntae6942 commented on src/main/java/blackjack/view/OutputView.java
> +    public void playerResult(PlayerDto playerDto) {
이부분은 수정해보겠습니다.

2024-01-21 02:48 UTC, juntae6942 commented on src/main/java/blackjack/service/PlayGameService.java
> +    public DealerDto returnDealerState() {
동사를 사용해서 좀 더 이해를 도울려는 목적이었는데 다른 사람이 보기에 이해에 도움이 안된다면 빼겠습니다😀

2024-01-21 02:54 UTC, juntae6942 commented on src/main/java/blackjack/domain/Dealer.java
> +    private static final int REPEAT_LIMIT = 16;
어떤 변수명이 좋을까요? 딱 떠오르는게 없어서 저렇게 썼거든요😀

2024-01-21 03:04 UTC, juntae6942 commented on src/main/java/blackjack/domain/Dealer.java
> +    public boolean scoreIsLowerThen16() {
메서드 사용하는 부분이 적은 부분이라서 유지 보수 측면에서 크게 문제가된다고 생각 안했는데 수정해보겠습니다😃

2024-01-21 03:08 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +            score+=10;
이 부분은 주석을 추가했습니다.😄

2024-01-21 03:12 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +        return cards.contains(new Card(CardSymbol.SPADE,1));
메서드명 수정했습니다 ✍️

2024-01-21 03:12 UTC, juntae6942 commented on src/main/java/blackjack/domain/Card.java
> +        return this.symbol.equals(CardSymbol.SPADE) && this.cardNumber==1;
수정했습니다.

2024-01-21 03:23 UTC, juntae6942 commented on src/main/java/blackjack/domain/CardSymbol.java
> +public enum CardSymbol {
이 부분은 저도 생각했었는데 난수 생성만 따로 빼는것이 좋을지 고민하다가 반영을 안했었는데, 수정해보겠습니다.😃

2024-01-21 03:23 UTC, juntae6942 commented on src/main/java/blackjack/dto/CardDto.java
> +    int num;
데이터 전달만 하는 DTO라서 신경을 덜 썼네요 수정하겠습니다

2024-01-21 04:32 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +    private static final int CHANGE_LIMIT = 11;
주석을 추가하겠습니다.

2024-01-22 03:52 UTC, shin-mallang requested changes
구현에 대해서는 보지 않았고, 코드 보는데 컨벤션 문서 읽고 코드 작성 부탁드립니다 ^^
혼난다 준태야 ^^

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/Card.java
> +    private final CardSymbol symbol;
공백

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/controller/BlackJackController.java
> +    public void playGame() throws IOException {
공백

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/CardSymbol.java
> +    final private String name;
공백,
final private -> private final

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/Dealer.java
> +    private int score;
공백

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/Player.java
> +    protected final List<Card> cards;
final
private
protected 순서

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/Player.java
> +    // 카드의 합이 11보다 작거나 같으면 Spade Ace를 1 -> 11
필요없는 주섯 제거

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/domain/Player.java
> +    }   // 스페이드 에이스인지 확인하고, 숫자를 1 -> 11로 변경하면서, 점수차 10점을 더한다.
필요없는 주석 제거

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/dto/CardDto.java
> +    CardSymbol symbol;
접근제어자 어디

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/dto/DealerDto.java
> +    private final List<Card> cards;
이거 붙일거면 붙이고 땔거면 떼주세요
통일이안돼있어용

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/dto/DealerDto.java
> +    }
생성자가 가장 먼저
getter는 가장 아래

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/dto/PlayerDto.java
> +    }
마찬가지

2024-01-22 03:52 UTC, shin-mallang commented on src/main/java/blackjack/service/PlayGameService.java
> +    private final Set<Card> duplicatedCheckCard;
공뱃

2024-01-22 04:41 UTC, juntae6942 commented
수정하였습니다.ㅎㅎ 아직 java convention에 대한 습관이 부족하네요..😅

2024-01-22 14:27 UTC, juntae6942 commented on src/main/java/blackjack/service/PlayGameService.java
> +        return !duplicatedCheckCard.contains(card);
수정했습니다.

2024-01-22 14:30 UTC, juntae6942 commented on src/main/java/blackjack/domain/Dealer.java
> +    private void checkIsAceAndChange(Card card) {
수정했습니다.

2024-01-22 14:35 UTC, juntae6942 commented on src/main/java/blackjack/view/InputView.java
> +public class InputView {
생각해보겠습니다😃

2024-01-22 14:38 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +    public boolean aceIsCanChange() {
이 부분은 제가 생각했을 때 크게 어색한 것 같지 않다고 생각합니다!

2024-01-22 14:39 UTC, juntae6942 commented on src/main/java/blackjack/service/PlayGameService.java
> +    public void gameStart() {
시작 = 카드 배분이라고 생각해서 메서드 명을 지었고, outPutView에 단순 print문만 추가하는 것이 좋지 않을 것 같아서 분류하지 않았습니다.🥹

2024-01-24 13:00 UTC, shin-mallang commented on src/main/java/blackjack/service/PlayGameService.java
> +public class PlayGameService {
Service 레이어를 왜 두었는지 의도가 궁금해요!
지금 Service 클래스는 조금 어정쩡 한 상태인 것 같습니다.
Controller에서 Service를 의존하는 구조인데도 불구하고 Service에서 View를 한번 더 의존하고 있네요.

2024-01-24 13:02 UTC, shin-mallang commented on src/main/java/blackjack/service/PlayGameService.java
> +        stringBuilder.append("무\n");
어떤곳은 21 그대로, 어떤곳은 BLACK_JACK 이라고 쓰여있네요.
그리고 메서드 길이도 너무 긴 것 같아요!

또한 DTO를 가지고 이러한 로직을 수행하는게 맞는 것인지 다시 한번 고민해보셨으면 좋겠습니다.
service layer의 역할, dto의 역할, controller의 역할 등에 대해 고민해 보셨으면 좋겟어요

2024-01-24 13:02 UTC, shin-mallang commented on src/main/java/blackjack/view/InputView.java
> +public class InputView {
생각의 결과를 알려주세요 !

2024-01-24 13:49 UTC, juntae6942 commented on src/main/java/blackjack/BlackJackApplication.java
> +    public static void main(String[] args) throws IOException {
수정했습니다!

2024-01-24 13:49 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +    public boolean spadeAceContains() {
수정했습니다!

2024-01-24 14:01 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +    protected final List<Card> cards;
수정했습니다!

2024-01-24 14:01 UTC, juntae6942 commented on src/main/java/blackjack/dto/DealerDto.java
> +    private final int score;
수정했습니다!

2024-01-24 14:14 UTC, shin-mallang commented on src/main/java/blackjack/service/PlayGameService.java
> +    public DealerDto returnDealerState() {
@juntae6942 이런 경우에는 getDealerState가 일반적으로 사용됩니당

2024-01-24 18:29 UTC, juntae6942 commented on src/main/java/blackjack/controller/BlackJackController.java
> +    }
수정했습니다!

2024-01-24 18:31 UTC, juntae6942 commented on src/main/java/blackjack/domain/Player.java
> +    }
이 부분에 대해서 생각을 해봤는데 도메인의 DTO 의존은 Controller에서 View로 DTO를 넘길때 도메인의 불필요한 부분까지 넘길 수 있어서 좋지 않다는걸 알았습니다. 그래서 데이터만 넘겨서 전달하게끔 바꿔 보았습니다!

2024-01-25 09:18 UTC, juntae6942 commented on src/main/java/blackjack/service/PlayGameService.java
> +public class PlayGameService {
컨트롤러에서 너무 많은 로직을 수행하는 것을 줄이기 위해서 서비스를 도입한다고 생각해서 사용하였습니다! View의 의존을 없애도록 코드를 수정하겠습니다!

2024-01-25 09:29 UTC, juntae6942 commented on src/main/java/blackjack/service/PlayGameService.java
> +        stringBuilder.append("무\n");
DTO를 단순 데이터 전달을 위한 용도로만 사용해야 하는데 로직을 수행하는 것에 사용했네요..수정하겠습니다!

2024-01-28 05:46 UTC, shin-mallang approved these changes
1단계 미션 고생하셨어요~~~
너무 늦어져서 남은 리뷰는 2단계 진행하면서 고쳐주시면 감사하겠습니다 :) 
코드 스타일이 많이 좋가진 것 같아요 ㅎㅎ

2024-01-28 05:46 UTC, shin-mallang commented on src/main/java/blackjack/dto/Result.java
> +    }
dto에 이러한 로직이 들어가도 문제없을까요?

2024-01-28 05:46 UTC, shin-mallang commented on src/main/java/blackjack/controller/BlackJackController.java
> +            Player player = new Player(playerName);
플레이어를 매번 생성하는 이유가 뭘까요?

2024-01-28 05:46 UTC, shin-mallang commented on src/main/java/blackjack/view/InputView.java
> +        bufferedReader = new BufferedReader(new InputStreamReader(System.in));
매번 새로 생성하는 이유가 있나요?

2024-01-28 05:46 UTC, shin-mallang commented on src/main/java/blackjack/view/InputView.java
> +        }   // player 의 수를 제한
이건 View에서 검증해야 할 사항일까요?
도메인의 규칙 아닐까요?

2024-01-28 05:46 UTC, shin-mallang commented on src/test/java/blackjack/service/PlayGameServiceTest.java
> +class PlayGameServiceTest {
dealer랑 service layer에 대한 테스트는 없네용~

2024-01-28 05:46 UTC, merged

2024-01-30 02:22 UTC, juntae6942 commented on src/main/java/blackjack/controller/BlackJackController.java
> +            Player player = new Player(playerName);
수정했습니다!

2024-01-30 02:40 UTC, juntae6942 commented on src/main/java/blackjack/view/InputView.java
> +        bufferedReader = new BufferedReader(new InputStreamReader(System.in));
수정했습니다!

2024-01-30 02:41 UTC, juntae6942 commented on src/main/java/blackjack/view/InputView.java
> +        }   // player 의 수를 제한
수정했습니다!